---
- name: hosts_localhost
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: '.*{{ ansible_hostname }}$'
    line: "{{ ansible_default_ipv4 }} {{ ansible_fqdn }} {{ ansible_hostname }}"
